from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BiosignalViewe(object):
    def setupUi(self, BiosignalViewe):
        BiosignalViewe.setObjectName("BiosignalViewe")
        BiosignalViewe.resize(1096, 787)
        self.centralwidget = QtWidgets.QWidget(BiosignalViewe)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(690, 630, 321, 80))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 30, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 30, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 30, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 610, 551, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 15, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(22, 40, 241, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(310, 20, 161, 51))
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 90, 1001, 501))
        self.frame.setStyleSheet("rgb (170, 170, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(50, 10, 71, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 10, 71, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(200, 10, 81, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(310, 10, 71, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(410, 10, 81, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(520, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setGeometry(QtCore.QRect(620, 10, 51, 31))
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(700, 15, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame)
        self.spinBox_2.setGeometry(QtCore.QRect(790, 10, 51, 31))
        self.spinBox_2.setObjectName("spinBox_2")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(60, 100, 811, 80))
        self.widget.setStyleSheet("rgb (0, 0, 0)")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setGeometry(QtCore.QRect(60, 190, 811, 80))
        self.widget_2.setStyleSheet("rgb (0, 0, 0)")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setGeometry(QtCore.QRect(60, 280, 811, 80))
        self.widget_3.setStyleSheet("rgb (0, 0, 0)")
        self.widget_3.setObjectName("widget_3")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.frame)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(70, 460, 791, 21))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.widget_4 = QtWidgets.QWidget(self.frame)
        self.widget_4.setGeometry(QtCore.QRect(59, 370, 811, 80))
        self.widget_4.setStyleSheet("rgb (0, 0, 0)")
        self.widget_4.setObjectName("widget_4")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 0, 1001, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(740, 30, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        BiosignalViewe.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BiosignalViewe)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 26))
        self.menubar.setObjectName("menubar")
        self.menuch_1 = QtWidgets.QMenu(self.menubar)
        self.menuch_1.setObjectName("menuch_1")
        self.menuch_2 = QtWidgets.QMenu(self.menubar)
        self.menuch_2.setObjectName("menuch_2")
        self.menuch_3 = QtWidgets.QMenu(self.menubar)
        self.menuch_3.setObjectName("menuch_3")
        BiosignalViewe.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BiosignalViewe)
        self.statusbar.setObjectName("statusbar")
        BiosignalViewe.setStatusBar(self.statusbar)
        self.actionchoice = QtWidgets.QAction(BiosignalViewe)
        self.actionchoice.setObjectName("actionchoice")
        self.actionchoice_2 = QtWidgets.QAction(BiosignalViewe)
        self.actionchoice_2.setObjectName("actionchoice_2")
        self.actionchoice_3 = QtWidgets.QAction(BiosignalViewe)
        self.actionchoice_3.setObjectName("actionchoice_3")
        self.actionchoice_4 = QtWidgets.QAction(BiosignalViewe)
        self.actionchoice_4.setObjectName("actionchoice_4")
        self.menuch_1.addAction(self.actionchoice)
        self.menuch_2.addAction(self.actionchoice_2)
        self.menuch_3.addAction(self.actionchoice_3)
        self.menubar.addAction(self.menuch_1.menuAction())
        self.menubar.addAction(self.menuch_2.menuAction())
        self.menubar.addAction(self.menuch_3.menuAction())

        self.retranslateUi(BiosignalViewe)
        QtCore.QMetaObject.connectSlotsByName(BiosignalViewe)

    def retranslateUi(self, BiosignalViewe):
        _translate = QtCore.QCoreApplication.translate
        BiosignalViewe.setWindowTitle(_translate("BiosignalViewe", "MainWindow"))
        self.groupBox.setTitle(_translate("BiosignalViewe", "Process Control "))
        self.pushButton_2.setText(_translate("BiosignalViewe", "Save"))
        self.pushButton_3.setText(_translate("BiosignalViewe", "Report "))
        self.pushButton_4.setText(_translate("BiosignalViewe", "Help "))
        self.groupBox_2.setTitle(_translate("BiosignalViewe", "Instrument  control "))
        self.label_4.setText(_translate("BiosignalViewe", "file path "))
        self.pushButton.setText(_translate("BiosignalViewe", "Channel  Setting"))
        self.pushButton_8.setText(_translate("BiosignalViewe", "All"))
        self.pushButton_6.setText(_translate("BiosignalViewe", "Zoom"))
        self.pushButton_5.setText(_translate("BiosignalViewe", "Minimize"))
        self.pushButton_7.setText(_translate("BiosignalViewe", "Ann"))
        self.comboBox.setItemText(0, _translate("BiosignalViewe", "stack plot"))
        self.label.setText(_translate("BiosignalViewe", "current start "))
        self.label_2.setText(_translate("BiosignalViewe", "Window"))
        self.label_3.setWhatsThis(_translate("BiosignalViewe", "<html><head/><body><p>fffff<span style=\" color:#00aaff;\">fff</span></p></body></html>"))
        self.label_3.setText(_translate("BiosignalViewe", "Biosignal viewer"))
        self.menuch_1.setTitle(_translate("BiosignalViewe", "ch 1"))
        self.menuch_2.setTitle(_translate("BiosignalViewe", "ch 2"))
        self.menuch_3.setTitle(_translate("BiosignalViewe", "ch 3"))
        self.actionchoice.setText(_translate("BiosignalViewe", "choice"))
        self.actionchoice.setShortcut(_translate("BiosignalViewe", "Ctrl+1"))
        self.actionchoice_2.setText(_translate("BiosignalViewe", "choice"))
        self.actionchoice_2.setShortcut(_translate("BiosignalViewe", "Ctrl+2"))
        self.actionchoice_3.setText(_translate("BiosignalViewe", "choice"))
        self.actionchoice_3.setShortcut(_translate("BiosignalViewe", "Ctrl+3"))
        self.actionchoice_4.setText(_translate("BiosignalViewe", "choice"))
        self.actionchoice_4.setShortcut(_translate("BiosignalViewe", "Ctrl+4"))
